
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: wael
      POSTGRES_PASSWORD: root
      POSTGRES_DB: inventory
    ports:
      - "5432:5432"
    volumes:
      - my_postgres_data:/var/lib/postgresql/data

volumes:
  my_postgres_data:
